### PR TITLE
Release/3.2.0

### PR DESCRIPTION
**Pull request by rhyslbw**
We just need to consider what we want to do with the Readme at this point. It's maybe a little early to be pointing over to the external documentation, or do we just want to do it anyway?

### CODE REVIEW

**Comment by DominikGuzei** [comment]
Let's point to the readme when we feel that it is decently finished :wink:

**Comment by rhyslbw** [comment]
The current Readme is out of date, needs technical review

**Comment by DominikGuzei** [comment]
let's put it on trello – IMO readme updates don't have to follow release cycles / should not stop publishing to atmosphere. Pretty much every readme is out of date atm :wink:

**Comment by rhyslbw** [comment]
k np

**Comment by DominikGuzei** [comment]
Ah ok, but we should wait with merging to master until the `meteor publish` works. Because for me it fails:
```
Macintosh:base dominik$ meteor publish
space:base: updating npm dependencies -- getenv...
=> Babel active on file extensions: es6.js, es6, jsx
                                              
/Users/dominik/.meteor/packages/meteor-tool/.1.1.10.7u2eij++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: ENOENT, stat '/Users/dominik/work/projects/opensource/meteor/space/base/.npm/package/npm-shrinkwrap.json'
    at Object.Future.wait (/Users/dominik/.meteor/packages/meteor-tool/.1.1.10.7u2eij++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at /tools/fs/files.js:1331:28
    at Object.wrapper [as stat] (/tools/fs/files.js:1334:20)
    at Object.files.copyFile (/tools/fs/files.js:549:21)
    at /tools/packaging/package-client.js:267:11
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/dominik/.meteor/packages/meteor-tool/.1.1.10.7u2eij++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at bundleSource (/tools/packaging/package-client.js:266:5)
    at /tools/packaging/package-client.js:706:26
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at Object.exports.publishPackage (/tools/packaging/package-client.js:705:16)
    at /tools/cli/commands-packages.js:432:21
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at Object.main.captureAndExit (/tools/cli/main.js:268:29)
    at Command.main.registerCommand.name [as func] (/tools/cli/commands-packages.js:428:8)
    at /tools/cli/main.js:1378:23
    - - - - -
```

**Comment by rhyslbw** [comment]
This PR was against master being the release branch

**Comment by DominikGuzei** [comment]
yeah, no worries – i just meant that we should "check" in the release branch if the actual publishing to atmosphere works. Because now we have the code in master but it does not work (cannot publish the release).

**Comment by rhyslbw** [comment]
Ah I see, misunderstood. Agreed

**Pull request merged**
