### PR TITLE
introduce better namespacing and class lookup

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR introduces a backward compatible way to define classes with fully qualified class path like this:
```javascript
// Anonymous namespace -> not on global scope!
Space.namespace('My.custom')
FirstClass = Space.Object.extend('My.custom.FirstClass', {})
Space.resolvePath('My.custom.FirstClass') // == FirstClass
```
or like this:
```javascript
// Namespace assigned to global scope
My.custom = Space.namespace('My.custom')
FirstClass = Space.Object.extend(My.custom, 'FirstClass', {})
Space.resolvePath('My.custom.FirstClass') // == FirstClass
```
which does a few things for us:

- Registers a `Space.Namespace` with the path `My.custom`
- Creates a class `FirstClass` which is attached to the namespace
- `FirstClass.classPath` and `FirstClass.toString()` returns the full path `'My.custom.FirstClass'`
- This is now default for *all* classes, so we can remove `FirstClass.type('My.custom.FirstClass')` from our code (this is done by `Space.Object.extend` now)

if you use Coffeescript with the `class` syntax, you still have to call `@type 'My.custom.FirstClass'` though since we have no control over the extension process there.

```coffeescript
# Namespace assigned to global scope
My.custom = Space.namespace('My.custom')
class FirstClass extends Space.Object
  @type 'My.custom.FirstClass'
Space.resolvePath('My.custom.FirstClass') // == FirstClass
```

### CODE REVIEW

**Comment by rhyslbw** [comment]
What's the status here @darko-mijic ? Are we leaving this open while migrating the other packages and apps?

@Sanjo thoughts on this?

**Comment by darko-mijic** [comment]
We should migrate all dependent packages first. There are too much packages dependent on the develop branch of base. VOs would brake if we merge this now.

**Comment by rhyslbw** [comment]
@darko-mijic So it's not backwards compatible? Whatever the case be good to keep any specific discussion relating to a PR in the PR so it's easily reviewed

**Comment by darko-mijic** [comment]
Registering a type causes an error. Like `Password.type('Password');`.
I think we should accept this breaking change and avoid introducing messy code for backwards compatibility. Especially since we have other breaking changes like serialization...

**Comment by rhyslbw** [comment]
It's important we get this merged now. Maybe we can divide up the packages to migrate?

**Comment by darko-mijic** [comment]
Readme needs to be updated and code snippets from Dominiks first comment added.

**Pull request merged**
