### PR TITLE
Hotifx/dependency annotation improvements

### PR DESCRIPTION
**Pull request by Sanjo**

### CODE REVIEW

**Comment by Sanjo** [comment]
For the master branch dependencies and requiredModules must start with an upper case.

**Comment by Sanjo** [comment]
Oh, I should have done this actually based on the master branch anyway ~.~

**Comment by Sanjo** [comment]
Here is the change for the master branch: https://github.com/Sanjo/meteor-space/tree/hotfix/master-dependency-annotations-improvements

**Comment by DominikGuzei** [comment]
Hey @Sanjo, the master branch is very far behind – `develop` is the current state and everything should be based on that :wink: We made many improvements and changes since the last release. We know that wasn't the "best" way to go, but there are also many breaking changes. Thanks for this update, looks great!

**Pull request merged**
