### PR TITLE
Fix package information for publishing to atmosphere

### PR DESCRIPTION
**Pull request by darko-mijic**
I had to specify minimum package version for core packages.

### CODE REVIEW

**Comment by darko-mijic** [comment]
@DominikGuzei

Can we remove this:
https://github.com/meteor-space/base/blob/chore/prepeare-package-for-publishing/package.js#l78

And update this:
https://github.com/meteor-space/base/blob/chore/prepeare-package-for-publishing/tests/unit/injector_annotations.unit.es6

**Comment by darko-mijic** [comment]
What do you thing the minimum dependency for core Meteor packages should be:
https://github.com/meteor-space/base/blob/chore/prepeare-package-for-publishing/package.js#l16

**Comment by darko-mijic** [comment]
Disregard my comment about annotations...

**Comment by rhyslbw** [comment]
Is there a reason for needing 1.2 ? We've only been requiring 1.0 up to this point

**Comment by darko-mijic** [comment]
we can not publish anything that requires `ecmascript`without this
1.0 won’t work

**Comment by rhyslbw** [comment]
Then we have a reason to require 1.2 :-) That should be fine :+1:

**Pull request merged**
