### PR TITLE
injectInto only once (fixes #7)

### LINKED ISSUE #7: When two components depend on each other it causes an infinite loop

### PR DESCRIPTION
**Pull request by Sanjo**
This fixes infinite loops when two components depend on each other.

### CODE REVIEW

**Comment by DominikGuzei** [comment]
Thanks for this patch! :wink:

**Comment by DominikGuzei** [comment]
This patch is included in the latest release `space:base@2.5.1`

**Comment by Sanjo** [comment]
Ah, ok. You can close my other PR if you already have got the commit into develop. Can you make develop the default branch on GitHub? Then PRs use develop as default.

**Comment by DominikGuzei** [comment]
Yeah, good idea :wink: thanks again for the contribution!

**Pull request merged**
